<?php
return [
    // Navigation and Interface
    'welcome' => 'Welcome to SIGDoc',
    'login' => 'Login',
    'logout' => 'Logout',
    'dashboard' => 'Dashboard',
    'documents' => 'Documents',
    'users' => 'Users',
    'settings' => 'Settings',
    'language' => 'Language',
    'home' => 'Home',
    'profile' => 'Profile',
    'search' => 'Search',
    'close' => 'Close',
    'back' => 'Back',
    'next' => 'Next',
    'previous' => 'Previous',
    'first' => 'First',
    'last' => 'Last',
    
    // Actions
    'save' => 'Save',
    'cancel' => 'Cancel',
    'edit' => 'Edit',
    'delete' => 'Delete',
    'view' => 'View',
    'add' => 'Add',
    'create' => 'Create',
    'update' => 'Update',
    'remove' => 'Remove',
    'confirm' => 'Confirm',
    'yes' => 'Yes',
    'no' => 'No',
    'send' => 'Send',
    'upload' => 'Upload',
    'download' => 'Download',
    'export' => 'Export',
    'import' => 'Import',
    'restore' => 'Restore',
    'archive' => 'Archive',
    'activate' => 'Activate',
    'deactivate' => 'Deactivate',
    'refresh' => 'Refresh',
    'reload' => 'Reload',
    
    // Forms
    'new_document' => 'New Document',
    'edit_document' => 'Edit Document',
    'view_document' => 'View Document',
    'current_version' => 'Current Version',
    'download_file' => 'Download File',
    'confirm_receipt' => 'Confirm Receipt',
    'movement_history' => 'Movement History',
    'no_movements_recorded' => 'No movements recorded.',
    'document_versions' => 'Document Versions',
    'current' => 'Current',
    'observations' => 'Observations',
    'restore' => 'Restore',
    'restore_version_confirm' => 'Restore version',
    'upload_new_version' => 'Upload New Version',
    'describe_changes_placeholder' => 'Describe the changes in this version...',
    'document_information' => 'Document Information',
    'total_versions' => 'Total Versions',
    'new_user' => 'New User',
    'email' => 'Email',
    'password' => 'Password',
    'confirm_password' => 'Confirm Password',
    'full_name' => 'Full Name',
    'name' => 'Name',
    'description' => 'Description',
    'title' => 'Title',
    'content' => 'Content',
    'file' => 'File',
    'choose_file' => 'Choose file',
    'select_option' => 'Select an option',
    'required_field' => 'Required field',
    'optional_field' => 'Optional field',
    
    // Categories and Status
    'public' => 'Public',
    'private' => 'Private',
    'confidential' => 'Confidential',
    'secret' => 'Secret',
    'active' => 'Active',
    'inactive' => 'Inactive',
    'archived' => 'Archived',
    'pending' => 'Pending',
    'approved' => 'Approved',
    'rejected' => 'Rejected',
    'urgent' => 'Urgent',
    'normal' => 'Normal',
    'low' => 'Low',
    'medium' => 'Medium',
    'high' => 'High',
    
    // Statistics and Reports
    'statistics' => 'Statistics',
    'total_documents' => 'Total Documents',
    'documents_this_month' => 'Documents this Month',
    'active_users' => 'Active Users',
    'movements' => 'Movements',
    'documents_by_status' => 'Documents by Status',
    'documents_by_sector' => 'Documents by Sector',
    'total' => 'Total',
    'count' => 'Count',
    'percentage' => 'Percentage',
    
    // Notifications and Alerts
    'notifications' => 'Notifications',
    'alerts' => 'Alerts',
    'attention' => 'Attention',
    'warning' => 'Warning',
    'error' => 'Error',
    'success' => 'Success',
    'info' => 'Information',
    'important' => 'Important',
    'deadline' => 'Deadline',
    'expired' => 'Expired',
    'expires_soon' => 'Expires soon',
    'overdue' => 'Overdue',
    
    // Dates and Time
    'date' => 'Date',
    'time' => 'Time',
    'datetime' => 'Date/Time',
    'created' => 'Created',
    'updated' => 'Updated',
    'modified' => 'Modified',
    'last_access' => 'Last Access',
    'expiration_date' => 'Expiration Date',
    'creation_date' => 'Creation Date',
    'modification_date' => 'Modification Date',
    
    // Areas and Sectors
    'area' => 'Area',
    'sector' => 'Sector',
    'department' => 'Department',
    'origin_area' => 'Origin Area',
    'destination_area' => 'Destination Area',
    'origin' => 'Origin',
    'destination' => 'Destination',
    'source' => 'Source',
    'target' => 'Target',
    
    // Types and Categories
    'type' => 'Type',
    'category' => 'Category',
    'classification' => 'Classification',
    'priority' => 'Priority',
    'status' => 'Status',
    'state' => 'State',
    'level' => 'Level',
    'group' => 'Group',
    
    // Users and Profiles
    'user' => 'User',
    'users' => 'Users',
    'administrator' => 'Administrator',
    'manager' => 'Manager',
    'collaborator' => 'Collaborator',
    'visitor' => 'Visitor',
    'role' => 'Role',
    'permission' => 'Permission',
    'access_level' => 'Access Level',
    'profile' => 'Profile',
    'account' => 'Account',
    'session' => 'Session',
    
    // Documents
    'document' => 'Document',
    'documents' => 'Documents',
    'version' => 'Version',
    'versions' => 'Versions',
    'history' => 'History',
    'revision' => 'Revision',
    'attachment' => 'Attachment',
    'file_size' => 'File Size',
    'file_type' => 'File Type',
    'file_name' => 'File Name',
    'file_path' => 'File Path',
    'file_extension' => 'File Extension',
    
    // Audit and Logs
    'audit' => 'Audit',
    'audit_log' => 'Audit Log',
    'access_log' => 'Access Log',
    'user_activity' => 'User Activity',
    'system_log' => 'System Log',
    'action' => 'Action',
    'actions' => 'Actions',
    'ip_address' => 'IP Address',
    'browser' => 'Browser',
    'operating_system' => 'Operating System',
    
    // System and Configuration
    'system' => 'System',
    'configuration' => 'Configuration',
    'settings' => 'Settings',
    'preferences' => 'Preferences',
    'options' => 'Options',
    'security' => 'Security',
    'backup' => 'Backup',
    'restore' => 'Restore',
    'maintenance' => 'Maintenance',
    'performance' => 'Performance',
    'optimization' => 'Optimization',
    
    // System Messages
    'welcome_message' => 'Welcome, {name}! 👋',
    'system_welcome' => 'You are logged into the Document Management System (SIGDoc).',
    'loading' => 'Loading...',
    'updating' => 'Updating...',
    'processing' => 'Processing...',
    'saving' => 'Saving...',
    'deleting' => 'Deleting...',
    'exporting' => 'Exporting...',
    'importing' => 'Importing...',
    'uploading' => 'Uploading...',
    'downloading' => 'Downloading...',
    
    // Success Messages
    'success_saved' => 'Saved successfully!',
    'success_created' => 'Created successfully!',
    'success_updated' => 'Updated successfully!',
    'success_deleted' => 'Deleted successfully!',
    'success_uploaded' => 'Uploaded successfully!',
    'success_downloaded' => 'Downloaded successfully!',
    'success_exported' => 'Exported successfully!',
    'success_imported' => 'Imported successfully!',
    
    // Error Messages
    'error_occurred' => 'An error occurred!',
    'error_saving' => 'Error saving!',
    'error_creating' => 'Error creating!',
    'error_updating' => 'Error updating!',
    'error_deleting' => 'Error deleting!',
    'error_uploading' => 'Error uploading!',
    'error_downloading' => 'Error downloading!',
    'error_exporting' => 'Error exporting!',
    'error_importing' => 'Error importing!',
    'error_loading' => 'Error loading!',
    'error_processing' => 'Error processing!',
    
    // Confirmations
    'confirm_delete' => 'Are you sure you want to delete?',
    'confirm_logout' => 'Are you sure you want to logout?',
    'confirm_cancel' => 'Are you sure you want to cancel?',
    'confirm_unsaved_changes' => 'There are unsaved changes. Do you want to leave anyway?',
    
    // Modal and Forms
    'create_new_user' => 'Create New User',
    'edit_user' => 'Edit User',
    'user_information' => 'User Information',
    'access_profile' => 'Access Profile',
    'profile_information' => 'Profile information:',
    'administrator_description' => 'Administrator - Full system control',
    'manager_description' => 'Manager - Can manage documents and users',
    'collaborator_description' => 'Collaborator - Can create and edit documents',
    'visitor_description' => 'Visitor - Only public document viewing',
    
    // Dashboard and Panel
    'management_panel' => 'Management Panel',
    'quick_actions' => 'Quick Actions',
    'recent_activities' => 'Recent Activities',
    'system_status' => 'System Status',
    'online' => 'Online',
    'offline' => 'Offline',
    'maintenance_mode' => 'Maintenance Mode',
    
    // Development
    'developed_in' => 'Developed in',
    'version' => 'Version',
    'copyright' => 'Copyright',
    'all_rights_reserved' => 'All rights reserved',
    
    // Language Selection
    'select_language' => 'Select language',
    'language_demo' => 'Language Demo',
    'current_language' => 'Current language',
    'translated_texts' => 'Translated Texts',
    'navigation' => 'Navigation',
    'system_information' => 'System Information',
    'or' => 'or',
    'last' => 'last',
    'management' => 'Management',
    'all' => 'All',
    'categories' => 'categories',
    'priorities' => 'priorities',
    'in_analysis' => 'In Analysis',
    'keyword' => 'Keyword',
    'filter' => 'Filter',
    'restricted' => 'Restricted',
    'showing' => 'Showing',
    'to' => 'to',
    'of' => 'of',
    'access_category' => 'Access Category',
    'keywords' => 'Keywords',
    'separated_by_comma' => 'separated by comma',
    'due_date' => 'due date',
    'public_documents' => 'Public documents',
    'private_documents' => 'Private documents',
    'confidential_documents' => 'Confidential documents',
    'secret_documents' => 'Secret documents',
    // Valores do banco de dados em português (traduzidos para inglês)
    'publico' => 'Public',
    'privado' => 'Private',
    'confidencial' => 'Confidential',
    'secreto' => 'Secret',
    'baixa' => 'Low',
    'media' => 'Medium',
    'alta' => 'High',
    // Valores de estado do banco de dados (traduzidos para inglês)
    'pendente' => 'Pending',
    'em_analise' => 'In Analysis',
    'aprovado' => 'Approved',
    'arquivado' => 'Archived',
    'rascunho' => 'Draft',
    'rejeitado' => 'Rejected',
    'welcome_subtitle' => 'Organize, protect and access your documents with security and efficiency.',
    'hello' => 'Hello!',
    'welcome_card_message' => 'This is your centralized environment for institutional document management.<br>Use the top menu to access system features.',
    'welcome_card_support' => 'If you have any questions, contact technical support.',
]; 