<?php
return [
    // Navegação e Interface
    'welcome' => 'Bem-vindo ao SIGDoc',
    'login' => 'Entrar',
    'logout' => 'Sair',
    'dashboard' => 'Painel',
    'documents' => 'Documentos',
    'users' => 'Usuários',
    'settings' => 'Configurações',
    'language' => 'Idioma',
    'home' => 'Início',
    'profile' => 'Perfil',
    'search' => 'Buscar',
    'close' => 'Fechar',
    'back' => 'Voltar',
    'next' => 'Próximo',
    'previous' => 'Anterior',
    'first' => 'Primeiro',
    'last' => 'Último',
    
    // Ações
    'save' => 'Salvar',
    'cancel' => 'Cancelar',
    'edit' => 'Editar',
    'delete' => 'Excluir',
    'view' => 'Visualizar',
    'add' => 'Adicionar',
    'create' => 'Criar',
    'update' => 'Atualizar',
    'remove' => 'Remover',
    'confirm' => 'Confirmar',
    'yes' => 'Sim',
    'no' => 'Não',
    'send' => 'Enviar',
    'upload' => 'Enviar',
    'download' => 'Baixar',
    'export' => 'Exportar',
    'import' => 'Importar',
    'restore' => 'Restaurar',
    'archive' => 'Arquivar',
    'activate' => 'Ativar',
    'deactivate' => 'Desativar',
    'refresh' => 'Atualizar',
    'reload' => 'Recarregar',
    
    // Formulários
    'new_document' => 'Novo Documento',
    'edit_document' => 'Editar Documento',
    'view_document' => 'Visualizar Documento',
    'current_version' => 'Versão Atual',
    'download_file' => 'Baixar Arquivo',
    'confirm_receipt' => 'Confirmar Recebimento',
    'movement_history' => 'Histórico de Movimentações',
    'no_movements_recorded' => 'Nenhuma movimentação registrada.',
    'document_versions' => 'Versões do Documento',
    'current' => 'Atual',
    'observations' => 'Observações',
    'restore' => 'Restaurar',
    'restore_version_confirm' => 'Restaurar versão',
    'upload_new_version' => 'Upload Nova Versão',
    'describe_changes_placeholder' => 'Descreva as mudanças nesta versão...',
    'document_information' => 'Informações do Documento',
    'total_versions' => 'Total de Versões',
    'new_user' => 'Novo Usuário',
    'email' => 'E-mail',
    'password' => 'Senha',
    'confirm_password' => 'Confirmar Senha',
    'full_name' => 'Nome Completo',
    'name' => 'Nome',
    'description' => 'Descrição',
    'title' => 'Título',
    'content' => 'Conteúdo',
    'file' => 'Arquivo',
    'choose_file' => 'Escolher arquivo',
    'select_option' => 'Selecione uma opção',
    'required_field' => 'Campo obrigatório',
    'optional_field' => 'Campo opcional',
    
    // Categorias e Status
    'public' => 'Público',
    'private' => 'Privado',
    'confidential' => 'Confidencial',
    'secret' => 'Secreto',
    'active' => 'Ativo',
    'inactive' => 'Inativo',
    'archived' => 'Arquivado',
    'pending' => 'Pendente',
    'approved' => 'Aprovado',
    'rejected' => 'Rejeitado',
    'urgent' => 'Urgente',
    'normal' => 'Normal',
    'low' => 'Baixa',
    'medium' => 'Média',
    'high' => 'Alta',
    
    // Estatísticas e Relatórios
    'statistics' => 'Estatísticas',
    'total_documents' => 'Total de Documentos',
    'documents_this_month' => 'Documentos este Mês',
    'active_users' => 'Usuários Ativos',
    'movements' => 'Movimentações',
    'documents_by_status' => 'Documentos por Estado',
    'documents_by_sector' => 'Documentos por Setor',
    'total' => 'Total',
    'count' => 'Quantidade',
    'percentage' => 'Porcentagem',
    
    // Notificações e Alertas
    'notifications' => 'Notificações',
    'alerts' => 'Alertas',
    'attention' => 'Atenção',
    'warning' => 'Aviso',
    'error' => 'Erro',
    'success' => 'Sucesso',
    'info' => 'Informação',
    'important' => 'Importante',
    'deadline' => 'Prazo',
    'expired' => 'Expirado',
    'expires_soon' => 'Expira em breve',
    'overdue' => 'Vencido',
    
    // Datas e Tempo
    'date' => 'Data',
    'time' => 'Hora',
    'datetime' => 'Data/Hora',
    'created' => 'Criado',
    'updated' => 'Atualizado',
    'modified' => 'Modificado',
    'last_access' => 'Último Acesso',
    'expiration_date' => 'Data de Expiração',
    'creation_date' => 'Data de Criação',
    'modification_date' => 'Data de Modificação',
    
    // Áreas e Setores
    'area' => 'Área',
    'sector' => 'Setor',
    'department' => 'Departamento',
    'origin_area' => 'Área de Origem',
    'destination_area' => 'Área de Destino',
    'origin' => 'Origem',
    'destination' => 'Destino',
    'source' => 'Fonte',
    'target' => 'Destino',
    
    // Tipos e Categorias
    'type' => 'Tipo',
    'category' => 'Categoria',
    'classification' => 'Classificação',
    'priority' => 'Prioridade',
    'status' => 'Status',
    'state' => 'Estado',
    'level' => 'Nível',
    'group' => 'Grupo',
    
    // Usuários e Perfis
    'user' => 'Usuário',
    'users' => 'Usuários',
    'administrator' => 'Administrador',
    'manager' => 'Gestor',
    'collaborator' => 'Colaborador',
    'visitor' => 'Visitante',
    'role' => 'Função',
    'permission' => 'Permissão',
    'access_level' => 'Nível de Acesso',
    'profile' => 'Perfil',
    'account' => 'Conta',
    'session' => 'Sessão',
    
    // Documentos
    'document' => 'Documento',
    'documents' => 'Documentos',
    'version' => 'Versão',
    'versions' => 'Versões',
    'history' => 'Histórico',
    'revision' => 'Revisão',
    'attachment' => 'Anexo',
    'file_size' => 'Tamanho do Arquivo',
    'file_type' => 'Tipo de Arquivo',
    'file_name' => 'Nome do Arquivo',
    'file_path' => 'Caminho do Arquivo',
    'file_extension' => 'Extensão do Arquivo',
    
    // Auditoria e Logs
    'audit' => 'Auditoria',
    'audit_log' => 'Log de Auditoria',
    'access_log' => 'Log de Acesso',
    'user_activity' => 'Atividade do Usuário',
    'system_log' => 'Log do Sistema',
    'action' => 'Ação',
    'actions' => 'Ações',
    'ip_address' => 'Endereço IP',
    'browser' => 'Navegador',
    'operating_system' => 'Sistema Operacional',
    
    // Sistema e Configurações
    'system' => 'Sistema',
    'configuration' => 'Configuração',
    'settings' => 'Configurações',
    'preferences' => 'Preferências',
    'options' => 'Opções',
    'security' => 'Segurança',
    'backup' => 'Backup',
    'restore' => 'Restaurar',
    'maintenance' => 'Manutenção',
    'performance' => 'Performance',
    'optimization' => 'Otimização',
    
    // Mensagens do Sistema
    'welcome_message' => 'Bem-vindo(a), {name}! 👋',
    'system_welcome' => 'Você está logado no Sistema de Gestão Documental (SIGDoc).',
    'loading' => 'Carregando...',
    'updating' => 'Atualizando...',
    'processing' => 'Processando...',
    'saving' => 'Salvando...',
    'deleting' => 'Excluindo...',
    'exporting' => 'Exportando...',
    'importing' => 'Importando...',
    'uploading' => 'Enviando...',
    'downloading' => 'Baixando...',
    
    // Mensagens de Sucesso
    'success_saved' => 'Salvo com sucesso!',
    'success_created' => 'Criado com sucesso!',
    'success_updated' => 'Atualizado com sucesso!',
    'success_deleted' => 'Excluído com sucesso!',
    'success_uploaded' => 'Enviado com sucesso!',
    'success_downloaded' => 'Baixado com sucesso!',
    'success_exported' => 'Exportado com sucesso!',
    'success_imported' => 'Importado com sucesso!',
    
    // Mensagens de Erro
    'error_occurred' => 'Ocorreu um erro!',
    'error_saving' => 'Erro ao salvar!',
    'error_creating' => 'Erro ao criar!',
    'error_updating' => 'Erro ao atualizar!',
    'error_deleting' => 'Erro ao excluir!',
    'error_uploading' => 'Erro ao enviar!',
    'error_downloading' => 'Erro ao baixar!',
    'error_exporting' => 'Erro ao exportar!',
    'error_importing' => 'Erro ao importar!',
    'error_loading' => 'Erro ao carregar!',
    'error_processing' => 'Erro ao processar!',
    
    // Confirmações
    'confirm_delete' => 'Tem certeza que deseja excluir?',
    'confirm_logout' => 'Tem certeza que deseja sair?',
    'confirm_cancel' => 'Tem certeza que deseja cancelar?',
    'confirm_unsaved_changes' => 'Existem alterações não salvas. Deseja sair mesmo assim?',
    
    // Modal e Formulários
    'create_new_user' => 'Cadastrar Novo Usuário',
    'edit_user' => 'Editar Usuário',
    'user_information' => 'Informações do Usuário',
    'access_profile' => 'Perfil de Acesso',
    'profile_information' => 'Informações sobre os perfis:',
    'administrator_description' => 'Administrador - Controle total do sistema',
    'manager_description' => 'Gestor - Pode gerenciar documentos e usuários',
    'collaborator_description' => 'Colaborador - Pode criar e editar documentos',
    'visitor_description' => 'Visitante - Apenas visualização de documentos públicos',
    
    // Dashboard e Painel
    'management_panel' => 'Painel Gerencial',
    'quick_actions' => 'Ações Rápidas',
    'recent_activities' => 'Atividades Recentes',
    'system_status' => 'Status do Sistema',
    'online' => 'Online',
    'offline' => 'Offline',
    'maintenance_mode' => 'Modo Manutenção',
    
    // Desenvolvimento
    'developed_in' => 'Desenvolvido em',
    'version' => 'Versão',
    'copyright' => 'Direitos Autorais',
    'all_rights_reserved' => 'Todos os direitos reservados',
    
    // Seleção de Idioma
    'select_language' => 'Selecionar idioma',
    'language_demo' => 'Demo de Idioma',
    'current_language' => 'Idioma atual',
    'translated_texts' => 'Textos Traduzidos',
    'navigation' => 'Navegação',
    'system_information' => 'Informações do Sistema',
    'or' => 'ou',
    'last' => 'últimos',
    'management' => 'Gestão',
    'all' => 'Todos',
    'categories' => 'categorias',
    'priorities' => 'prioridades',
    'in_analysis' => 'Em Análise',
    'keyword' => 'Palavra-chave',
    'filter' => 'Filtrar',
    'restricted' => 'Restrito',
    'showing' => 'Mostrando',
    'to' => 'a',
    'of' => 'de',
    'access_category' => 'Categoria de Acesso',
    'keywords' => 'Palavras-chave',
    'separated_by_comma' => 'separadas por vírgula',
    'due_date' => 'data limite',
    'public_documents' => 'Documentos públicos',
    'private_documents' => 'Documentos privados',
    'confidential_documents' => 'Documentos confidenciais',
    'secret_documents' => 'Documentos secretos',
    // Valores do banco de dados em português
    'publico' => 'Público',
    'privado' => 'Privado',
    'confidencial' => 'Confidencial',
    'secreto' => 'Secreto',
    'baixa' => 'Baixa',
    'media' => 'Média',
    'alta' => 'Alta',
    // Valores de estado do banco de dados
    'pendente' => 'Pendente',
    'em_analise' => 'Em Análise',
    'aprovado' => 'Aprovado',
    'arquivado' => 'Arquivado',
    'rascunho' => 'Rascunho',
    'rejeitado' => 'Rejeitado',
    'welcome_subtitle' => 'Organize, proteja e acesse seus documentos com segurança e eficiência.',
    'hello' => 'Olá!',
    'welcome_card_message' => 'Este é o seu ambiente centralizado para gestão de documentos institucionais.<br>Utilize o menu superior para acessar as funcionalidades do sistema.',
    'welcome_card_support' => 'Em caso de dúvidas, procure o suporte técnico.',
]; 